-- Esquema
CREATE SCHEMA IF NOT EXISTS db_masterdatahub;

-- #####################################################################
-- Tablas
-- #####################################################################

-- Tabla: COMPANIA
CREATE TABLE IF NOT EXISTS db_masterdatahub.erp_COMPANIA (
    CODCIA NUMERIC(2) NOT NULL,
    NOMBRE VARCHAR(30),
    FEMOD TIMESTAMPTZ,
    PRIMARY KEY (CODCIA)
);

-- Tabla: MONEDA
CREATE TABLE IF NOT EXISTS db_masterdatahub.erp_MONEDA (
    COD_MON NUMERIC(2) NOT NULL,
    NOMBRE VARCHAR(30) NOT NULL,
    FEMOD TIMESTAMPTZ,
    PRIMARY KEY (COD_MON)
);

-- Tabla: PAIS
CREATE TABLE IF NOT EXISTS db_masterdatahub.erp_PAIS (
    COD_PAIS NUMERIC(3) NOT NULL,
    NOMBRE VARCHAR(30) NOT NULL,
    COD_MON NUMERIC(2),
    FEMOD TIMESTAMPTZ,
    PRIMARY KEY (COD_PAIS)
);

-- Tabla: CIUDAD
CREATE TABLE IF NOT EXISTS db_masterdatahub.erp_CIUDAD (
    COD_PAIS NUMERIC(3) NOT NULL,
    CIUDAD VARCHAR(5) NOT NULL,
    NOMBRE VARCHAR(30),
    SUBZONA NUMERIC(2),
    CLIMA NUMERIC(2),
    FEMOD TIMESTAMPTZ,
    PRIMARY KEY (COD_PAIS, CIUDAD)
);

-- Tabla: DEPENDENCIA
CREATE TABLE IF NOT EXISTS db_masterdatahub.erp_DEPENDENCIA (
    DEPEN NUMERIC(4) NOT NULL,
    NOMBRE VARCHAR(30) NOT NULL,
    FEMOD TIMESTAMPTZ,
    PRIMARY KEY (DEPEN)
);

-- Tabla: SUBLINEA
CREATE TABLE IF NOT EXISTS db_masterdatahub.erp_SUBLINEA (
    CODCIA NUMERIC(2) NOT NULL,
    SUBLIN NUMERIC(3) NOT NULL,
    NOMBRE VARCHAR(30),  
    FEMOD TIMESTAMPTZ,
    PRIMARY KEY (CODCIA, SUBLIN)
);

-- Tabla: CADENA
CREATE TABLE IF NOT EXISTS db_masterdatahub.erp_CADENA (
    CODCADE VARCHAR(1) NOT NULL,
    NOMBRE VARCHAR(30) NOT NULL,
    FEMOD TIMESTAMPTZ,
    PRIMARY KEY (CODCADE)
);

-- Tabla: GERENCIA
CREATE TABLE IF NOT EXISTS db_masterdatahub.erp_GERENCIA (
    CODCIA NUMERIC(2) NOT NULL,
    DIVIS NUMERIC(2) NOT NULL,
    NOMBRE VARCHAR(30),
    FEMOD TIMESTAMPTZ,
    PRIMARY KEY (CODCIA, DIVIS)
);

-- Tabla: CATEGORIA
CREATE TABLE IF NOT EXISTS db_masterdatahub.erp_CATEGORIA (
    CODCIA NUMERIC(2) NOT NULL,
    SUBLIN NUMERIC(3) NOT NULL,
    CATEGO NUMERIC(5) NOT NULL,
    NOMBRE VARCHAR(30),
    FEMOD TIMESTAMPTZ,
    PRIMARY KEY (CODCIA, SUBLIN, CATEGO)
);

-- Tabla: SUBCATEGORIA
CREATE TABLE IF NOT EXISTS db_masterdatahub.erp_SUBCATEGORIA (
    CODCIA NUMERIC(2) NOT NULL,
    GRUPO NUMERIC(4) NOT NULL,
    CATEGO NUMERIC(5) NOT NULL,
    NOMBRE VARCHAR(30),
    FEMOD TIMESTAMPTZ
);

-- Tabla: UEN
CREATE TABLE IF NOT EXISTS db_masterdatahub.erp_UEN (
    CODCIA NUMERIC(2) NOT NULL,
    DEPTO NUMERIC(2) NOT NULL,
    NOMBRE VARCHAR(30),
    DIVIS1 NUMERIC(2),
    FEMOD TIMESTAMPTZ,
    PRIMARY KEY (CODCIA, DEPTO)
);

-- Tabla: CANAL
CREATE TABLE IF NOT EXISTS db_masterdatahub.erp_CANAL (
    CANAL VARCHAR(2) NOT NULL,
    NOMBRE VARCHAR(30),
    FEMOD TIMESTAMPTZ,
    PRIMARY KEY (CANAL)
);

-- Tabla: SEGMENTOS
CREATE TABLE IF NOT EXISTS db_masterdatahub.erp_SEGMENTOS (
    CODCIA NUMERIC(2) NOT NULL,
    SUBLIN NUMERIC(3),
    SUBCATEGO NUMERIC(4),
    SEGMENS NUMERIC(4),
    NOMSEGS VARCHAR(30),
    FEMOD TIMESTAMPTZ,
    PRIMARY KEY (CODCIA)
);

-- Tabla: audit_log
CREATE TABLE IF NOT EXISTS db_masterdatahub.audit_log
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    procedure_name text COLLATE pg_catalog."default" NOT NULL,
    execution_time timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    end_time timestamp with time zone,
    user_name text COLLATE pg_catalog."default" NOT NULL,
    result_status text COLLATE pg_catalog."default" NOT NULL,
    error_message text COLLATE pg_catalog."default",
    parameters jsonb,
    result jsonb,
    duration interval,
    additional_info jsonb,
    CONSTRAINT audit_log_pkey PRIMARY KEY (id)
);

-- Función para actualizar FEMOD
CREATE OR REPLACE FUNCTION db_masterdatahub.update_femod_column()
RETURNS TRIGGER AS $$
BEGIN
   NEW.FEMOD = now() AT TIME ZONE 'America/Bogota';
   RETURN NEW;
END;
$$ language 'plpgsql';

-- Triggers para las tablas con FEMOD
DROP TRIGGER IF EXISTS update_compania_femod ON db_masterdatahub.erp_COMPANIA;
CREATE TRIGGER update_compania_femod BEFORE INSERT OR UPDATE ON db_masterdatahub.erp_COMPANIA FOR EACH ROW EXECUTE FUNCTION db_masterdatahub.update_femod_column();

DROP TRIGGER IF EXISTS update_moneda_femod ON db_masterdatahub.erp_MONEDA;
CREATE TRIGGER update_moneda_femod BEFORE INSERT OR UPDATE ON db_masterdatahub.erp_MONEDA FOR EACH ROW EXECUTE FUNCTION db_masterdatahub.update_femod_column();

DROP TRIGGER IF EXISTS update_pais_femod ON db_masterdatahub.erp_PAIS;
CREATE TRIGGER update_pais_femod BEFORE INSERT OR UPDATE ON db_masterdatahub.erp_PAIS FOR EACH ROW EXECUTE FUNCTION db_masterdatahub.update_femod_column();

DROP TRIGGER IF EXISTS update_ciudad_femod ON db_masterdatahub.erp_CIUDAD;
CREATE TRIGGER update_ciudad_femod BEFORE INSERT OR UPDATE ON db_masterdatahub.erp_CIUDAD FOR EACH ROW EXECUTE FUNCTION db_masterdatahub.update_femod_column();

DROP TRIGGER IF EXISTS update_dependencia_femod ON db_masterdatahub.erp_DEPENDENCIA;
CREATE TRIGGER update_dependencia_femod BEFORE INSERT OR UPDATE ON db_masterdatahub.erp_DEPENDENCIA FOR EACH ROW EXECUTE FUNCTION db_masterdatahub.update_femod_column();

DROP TRIGGER IF EXISTS update_sublinea_femod ON db_masterdatahub.erp_SUBLINEA;
CREATE TRIGGER update_sublinea_femod BEFORE INSERT OR UPDATE ON db_masterdatahub.erp_SUBLINEA FOR EACH ROW EXECUTE FUNCTION db_masterdatahub.update_femod_column();

DROP TRIGGER IF EXISTS update_cadena_femod ON db_masterdatahub.erp_CADENA;
CREATE TRIGGER update_cadena_femod BEFORE INSERT OR UPDATE ON db_masterdatahub.erp_CADENA FOR EACH ROW EXECUTE FUNCTION db_masterdatahub.update_femod_column();

DROP TRIGGER IF EXISTS update_gerencia_femod ON db_masterdatahub.erp_GERENCIA;
CREATE TRIGGER update_gerencia_femod BEFORE INSERT OR UPDATE ON db_masterdatahub.erp_GERENCIA FOR EACH ROW EXECUTE FUNCTION db_masterdatahub.update_femod_column();

DROP TRIGGER IF EXISTS update_categoria_femod ON db_masterdatahub.erp_CATEGORIA;
CREATE TRIGGER update_categoria_femod BEFORE INSERT OR UPDATE ON db_masterdatahub.erp_CATEGORIA FOR EACH ROW EXECUTE FUNCTION db_masterdatahub.update_femod_column();

DROP TRIGGER IF EXISTS update_subcategoria_femod ON db_masterdatahub.erp_SUBCATEGORIA;
CREATE TRIGGER update_subcategoria_femod BEFORE INSERT OR UPDATE ON db_masterdatahub.erp_SUBCATEGORIA FOR EACH ROW EXECUTE FUNCTION db_masterdatahub.update_femod_column();

DROP TRIGGER IF EXISTS update_uen_femod ON db_masterdatahub.erp_UEN;
CREATE TRIGGER update_uen_femod BEFORE INSERT OR UPDATE ON db_masterdatahub.erp_UEN FOR EACH ROW EXECUTE FUNCTION db_masterdatahub.update_femod_column();

DROP TRIGGER IF EXISTS update_canal_femod ON db_masterdatahub.erp_CANAL;
CREATE TRIGGER update_canal_femod BEFORE INSERT OR UPDATE ON db_masterdatahub.erp_CANAL FOR EACH ROW EXECUTE FUNCTION db_masterdatahub.update_femod_column();

DROP TRIGGER IF EXISTS update_segmentos_femod ON db_masterdatahub.erp_SEGMENTOS;
CREATE TRIGGER update_segmentos_femod BEFORE INSERT OR UPDATE ON db_masterdatahub.erp_SEGMENTOS FOR EACH ROW EXECUTE FUNCTION db_masterdatahub.update_femod_column();

-- #####################################################################
-- Procedimientos Almacenados
-- #####################################################################

-- Procedimiento para registrar logs
CREATE OR REPLACE PROCEDURE db_masterdatahub.sp_registrar_logs(
	IN nombre_proced text,
	IN tiempo_ejec_ini timestamp without time zone,
	IN tiempo_ejec_fin timestamp without time zone,
	IN estado text,
	IN mensaje_error text,
	IN parametros jsonb,
	IN resultado jsonb,
	IN info_adicional jsonb)
LANGUAGE 'plpgsql'
AS $BODY$
/***********************************************************************************************************************
Procedimiento: db_masterdatahub.sp_registrar_logs
Fecha de creación: 01-09-2025
Versión: 1.0.0
Descripción: Registra la ejecución de procedimientos en la tabla de auditoría.
***********************************************************************************************************************/
DECLARE
    tiempo_duracion INTERVAL;
BEGIN
    tiempo_duracion := tiempo_ejec_fin - tiempo_ejec_ini;
    INSERT INTO db_masterdatahub.audit_log (procedure_name, execution_time, end_time, user_name, result_status, error_message, parameters, result, duration, additional_info)
    VALUES (nombre_proced, tiempo_ejec_ini, tiempo_ejec_fin, current_user, estado, mensaje_error, parametros, resultado, tiempo_duracion, info_adicional);
    RAISE NOTICE 'logs registrados correctamente';
    EXCEPTION
    WHEN others THEN
    RAISE EXCEPTION 'ha ocurrido un error al registrar los logs -- error: %', SQLERRM;
END;
$BODY$;

-- FUNCTION: db_masterdatahub.upsert_marcas_json(jsonb)

-- DROP FUNCTION IF EXISTS db_masterdatahub.upsert_marcas_json(jsonb);

CREATE OR REPLACE FUNCTION db_masterdatahub.upsert_marcas_json(
	input_json jsonb)
    RETURNS jsonb
    LANGUAGE 'plpgsql'
    COST 100
    VOLATILE PARALLEL UNSAFE
AS $BODY$
DECLARE
    brand_element RECORD;
    v_brand_id INT;
BEGIN
    -- Iterar sobre cada marca en el JSON de entrada
    FOR brand_element IN SELECT * FROM jsonb_array_elements(input_json -> 'brands')
    LOOP
        v_brand_id := (brand_element ->> 'brandId')::INT;

        RAISE NOTICE 'Processing brandId: %', v_brand_id;

        -- 1. Insertar o actualizar el registro principal de la marca
        INSERT INTO db_masterdatahub.pim_brand_records (brand_id, "name", state_id, create_date, femod)
        VALUES (v_brand_id, brand_element ->> 'name', (brand_element ->> 'status')::BOOLEAN, NOW(), NOW())
        ON CONFLICT (brand_id) DO UPDATE
        SET "name" = EXCLUDED."name",
            state_id = EXCLUDED.state_id,
            femod = NOW();

        -- 2. Eliminar todos los atributos existentes para esta marca
        -- Es más simple y a menudo suficientemente rápido eliminar y volver a insertar.
        DELETE FROM db_masterdatahub.pim_brand_records_attributes WHERE brand_id = v_brand_id;
        DELETE FROM db_masterdatahub.pim_brand_records_multi_value_attributes WHERE brand_id = v_brand_id;

        -- 3. Insertar todos los atributos de valor simple en una sola operación
        IF jsonb_array_length(brand_element -> 'attributes') > 0 THEN
            INSERT INTO db_masterdatahub.pim_brand_records_attributes (brand_id, attribute_id, is_multi_value, value_text, value_id, femod)
            SELECT
                v_brand_id,
                attr ->> 'attributeId',
                FALSE,
                attr ->> 'valueText',
                attr ->> 'valueId',
                NOW()
            FROM jsonb_array_elements(brand_element -> 'attributes') AS attr;
        END IF;

        -- 4. Insertar los "headers" para los atributos multivalor
        IF jsonb_array_length(brand_element -> 'MultiValue') > 0 THEN
            INSERT INTO db_masterdatahub.pim_brand_records_attributes (brand_id, attribute_id, is_multi_value, femod)
            SELECT
                v_brand_id,
                mv_attr ->> 'attributeId',
                TRUE,
                NOW()
            FROM jsonb_array_elements(brand_element -> 'MultiValue') AS mv_attr;

            -- 5. Insertar todos los valores de los atributos multivalor en una sola operación
            INSERT INTO db_masterdatahub.pim_brand_records_multi_value_attributes (brand_id, attribute_id, value_id, value_text, femod)
            SELECT
                v_brand_id,
                mv_attr ->> 'attributeId',
                val ->> 'valueId',
                val ->> 'valueText',
                NOW()
            FROM jsonb_array_elements(brand_element -> 'MultiValue') AS mv_attr,
                 jsonb_array_elements(mv_attr -> 'attributes') AS val;
        END IF;

    END LOOP;

    RETURN jsonb_build_object('status', true, 'message', 'Marcas procesadas correctamente');
EXCEPTION
    WHEN OTHERS THEN
        RETURN jsonb_build_object('status', false, 'message', 'Error: ' || SQLERRM);
END;
$BODY$;

ALTER FUNCTION db_masterdatahub.upsert_marcas_json(jsonb)
    OWNER TO nifi_masterdatahub_dev;